// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require("prism-react-renderer").themes.github;
const darkCodeTheme = require("prism-react-renderer").themes.dracula;
const {GlobExcludeDefault} = require('@docusaurus/utils');
const fs = require("fs");
const path = require("path");
const isBlog = process.env.IS_BLOG === 'true';

// QoD version shown in the navbar badge; sourced from the generated OpenAPI
// spec so the badge and the /api/ reference can never disagree.
function readQodVersion() {
  try {
    const spec = fs.readFileSync(path.join(__dirname, "static", "openapi.yaml"), "utf8");
    const m = spec.match(/^\s+version:\s*(\S+)\s*$/m);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}
const qodVersion = readQodVersion();

// Newest released snapshot of each docs instance (first entry of its
// versions file). The LLM files index only these, never the Next tree.
const latestStarflowVersion = require("./versions.json")[0];
const latestQodVersion = require("./qod_versions.json")[0];

// Doc file globs in sidebar order, so llms.txt lists pages the way the
// sidebar does. Only needed for QoD: the Starflow sidebar is autogenerated
// from numeric prefixes, so its alphabetical order already matches.
function sidebarOrderGlobs(sidebarFile, docsDir) {
  const ids = [];
  const walk = (item) => {
    if (typeof item === "string") return ids.push(item);
    if (item.type === "doc") ids.push(item.id);
    if (item.link?.type === "doc") ids.push(item.link.id);
    (item.items || []).forEach(walk);
  };
  Object.values(require(sidebarFile)).flat().forEach(walk);
  return ids.map((id) => `${docsDir}/${id}.{md,mdx}`);
}

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Starlake",
  tagline: "Load and Transform your data declaratively",
  favicon: "img/favicon_starlake.ico",

  // Set the production url of your site here
  url: isBlog ? "https://blog.starlake.ai" : "https://docs.starlake.ai",
  baseUrl: "/",

  organizationName: "starlake-ai", // Usually your GitHub org/user name.
  projectName: "starlake", // Usually your repo name.

  onBrokenLinks: "throw",
  trailingSlash: false,
  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },
  presets: [
    [
      "classic",
      {
        docs: isBlog ? {
          path: 'blog-docs',  // Point to a different directory when in blog mode
          sidebarPath: require.resolve("./sidebars.js"),
          routeBasePath: '/docs',
          // versions.json belongs to the Starflow docs; ignore it here.
          disableVersioning: true,
        } : {
          path: 'docs',  // Regular docs directory
          sidebarPath: require.resolve("./sidebars.js"),
          routeBasePath: 'starflow',
          exclude: ['superpowers/**'],
          // Released snapshots live in versioned_docs/ (see versions.json);
          // docs/ is the unreleased tree, served under /starflow/next.
          versions: {
            current: { label: 'Next', noIndex: true },
          },
        },
        blog: isBlog ? {
          blogSidebarCount: 0,
          showReadingTime: true,
          routeBasePath: '/',
        } : {
          showReadingTime: true,
          routeBasePath: '/blog',
          exclude: ['**/*'],
        },
        pages: isBlog ? {
          // The qod/starflow landing pages link to docs routes that only
          // exist on the docs site, so they must not build in blog mode.
          exclude: [...GlobExcludeDefault, 'qod/**', 'starflow/**'],
        } : {},
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
        gtag: {
          trackingID: "G-FYS72XYD48",
          anonymizeIP: true,
        },
      },
    ],
  ],
  themeConfig: {
    docs: {
      sidebar: {
        autoCollapseCategories: true,
        hideable: false,
      },
    },
    prism: {
      additionalLanguages: ["java", "scala", "sql", "powershell", "python"],
      theme: lightCodeTheme,
    },
    // Replace with your project's social card
    colorMode: {
      defaultMode: "light",
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
    navbar: {
      title: "Starlake",
      logo: {
        alt: "Starlake",
        src: "img/starlake-logo.png",
        srcDark: "img/starlake-logo.png",
        href: "https://starlake.ai",
      },
      items: [
        isBlog ? {
          href: "https://docs.starlake.ai",
          label: "Documentation",
          position: "left",
        } : {
          to: "/starflow",
          label: "Starflow",
          position: "left",
        },
        !isBlog ? {
          to: "/qod",
          label: "Quack on Demand",
          position: "left",
        } : null,
        !isBlog ? {
          type: "custom-qodVersion",
          position: "left",
        } : null,
        !isBlog ? {
          href: "https://blog.starlake.ai",
          label: "Blog",
          position: "left",
        } : {
          to: "/",
          label: "Blog home",
          position: "left",
        },
        // One version dropdown per product, each shown only in its section.
        !isBlog ? {
          type: "custom-sectionVersionDropdown",
          docsPluginId: "default",
          position: "right",
        } : null,
        !isBlog ? {
          type: "custom-sectionVersionDropdown",
          docsPluginId: "qod",
          position: "right",
        } : null,
        /*
                {
                    href: 'https://search.maven.org/search?q=ai.starlake',
                    position: 'right',
                    className: 'header-download-link header-icon-link',
                    'aria-label': 'Download',
                },
                */
        {
          // No href: the link follows the section being browsed, so /qod
          // points at quack-on-demand and everything else at starlake.
          type: "custom-iconLink",
          icon: "github",
          position: "right",
        },
        {
          type: "custom-iconLink",
          icon: "discord",
          href: "https://discord.gg/6tNa7yCNqw",
          position: "right",
        },
      ].filter(Boolean),
    },
    //     footer: {
    //       style: "dark",
    //       links: [
    //         {
    //           items: [
    //             {
    //               label: "Documentation",
    //               to: "/docs/intro",
    //             },
    //             {
    //               label: "Blog",
    //               href: "/blog",
    //             },
    //           ],
    //         },

    //         {
    //           items: [
    //             {
    //               html: `
    // <ul class="footer_right"><li><a href="https://github.com/starlake-ai/starlake" target="_blank" rel="noopener noreferrer" class="navbar__item navbar__link header-github-link header-icon-link" aria-label="GitHub repository"></a></li><li><a href="https://join.slack.com/t/starlakeai/shared_invite/zt-28vf5d49s-rnyuh70OrJjcX_2Vz2mafw" target="_blank" rel="noopener noreferrer" class="navbar__item navbar__link header-slack-link header-icon-link" aria-label="Community"></a></li></ul>
    // `,
    //             },
    //           ],
    //         },
    //       ],
    //     },
    zoom: {
      selector: ".markdown :not(em) > img, .split_section .img-fluid",
      config: {
        // options you can specify via https://github.com/francoischalifour/medium-zoom#usage
        background: {
          light: "rgba(2, 0, 19, 0.5)",
          dark: "rgba(2, 0, 19, 0.5)",
        },
      },
    },
    image: "img/social-card.png",
    metadata: [
      {name: 'keywords', content: 'starlake, etl, data pipeline, data transformation, quack on demand, duckdb, ducklake, duckdb access control, duckdb acl, duckdb adbc, duckdb sso, duckdb authentication, duckdb multi-tenant, flight sql server'},
      {name: 'description', content: 'Documentation for Starlake, the declarative ETL platform, and Quack on Demand, the multi-tenant DuckDB gateway with access control, SSO, ADBC and Flight SQL.'},
    ],
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "name": "Starlake Documentation",
      "url": "https://docs.starlake.ai",
      "description": "Official documentation for Starlake - the open source declarative data pipeline platform",
      "publisher": {
        "@type": "Organization",
        "name": "Starlake",
        "logo": {
          "@type": "ImageObject",
          "url": "https://docs.starlake.ai/img/starlake-logo.png"
        }
      },
      "about": [
        {
          "@type": "SoftwareApplication",
          "name": "Starlake",
          "applicationCategory": "Data Loading & Transformation Platform",
          "operatingSystem": "Cross-platform",
          "description": "Open source declarative data pipeline platform: extract, load and transform with YAML and SQL.",
          "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD"
          }
        },
        {
          "@type": "SoftwareApplication",
          "name": "Quack on Demand",
          "applicationCategory": "Database Gateway",
          "operatingSystem": "Linux, macOS, Windows, Docker, Kubernetes",
          "url": "https://docs.starlake.ai/qod",
          "description": "Multi-tenant SQL gateway for DuckDB and DuckLake: authentication, SSO, role-based access control with row and column security, ADBC, JDBC and ODBC over Arrow Flight SQL, and native DuckDB ATTACH.",
          "keywords": "DuckDB, DuckLake, access control, ACL, RBAC, ADBC, Flight SQL, SSO, OAuth, OIDC, multi-tenant",
          "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD"
          }
        }
      ],
      "audience": {
        "@type": "Audience",
        "audienceType": "Data Engineers, Data Scientists, Enterprise IT Teams"
      },
      "mainEntity": {
        "@type": "TechArticle",
        "headline": "Starlake Documentation",
        "description": "Complete documentation for installing, configuring and using Starlake data pipeline platform",
        "articleSection": ["Installation", "Configuration", "Tutorials", "API Reference"],
        "keywords": "ETL, data pipeline, data transformation, data quality, data governance, DuckDB, DuckLake, access control, ADBC, Flight SQL, SSO"
      }
    }
  },

  plugins: [
    // /qod/choose was a standalone comparison page; the table it held now
    // lives at the end of the /qod landing page.
    !isBlog && [
      "@docusaurus/plugin-client-redirects",
      {
        redirects: [{ from: "/qod/choose", to: "/qod" }],
      },
    ],
    !isBlog && [
      "@docusaurus/plugin-content-docs",
      {
        id: "qod",
        path: "qod",
        routeBasePath: "qod",
        sidebarPath: require.resolve("./sidebars-qod.js"),
        editUrl: "https://github.com/starlake-ai/starlake-docs/tree/main/",
        // Released snapshots live in qod_versioned_docs/ (see
        // qod_versions.json); qod/ is the unreleased tree, under /qod/next.
        versions: {
          current: { label: "Next", noIndex: true },
        },
      },
    ],
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        hashed: true,
        docsRouteBasePath: isBlog ? '/docs/' : ['/starflow', '/qod'],
        blogRouteBasePath: isBlog ? '/blog/' : '/',
        ...(isBlog ? {} : {
          searchContextByPaths: ['qod'],
          hideSearchBarWithNoSearchContext: false,
        }),
      },
    ],
    // Writes llms.txt, llms-full.txt and a .md copy of every page at build
    // time, from the latest QoD and Starflow snapshots only.
    !isBlog && [
      "docusaurus-plugin-llms",
      {
        title: "Starlake",
        description:
          "Open-source declarative data pipeline platform for Extract, Load, and Transform operations using YAML and SQL, and Quack on Demand, a multi-tenant SQL gateway for DuckDB and DuckLake.",
        rootContent: [
          "Starlake lets data engineers build production data pipelines without writing Python or Scala. Define schemas, connections, and transformations in YAML and SQL. Starlake handles loading files (CSV, JSON, XML, fixed-width) into warehouses, extracting data from databases, running SQL/Python transforms, and auto-generating Airflow/Dagster DAGs from SQL dependency analysis. Supports BigQuery, Snowflake, Databricks, Spark, PostgreSQL, and DuckDB.",
          "",
          "Quack on Demand turns DuckDB and DuckLake into a governed service with authentication, single sign-on, role-based access control with row and column security, and ADBC, JDBC and ODBC access over Arrow Flight SQL.",
          "",
          `These files cover Quack on Demand ${latestQodVersion} and Starflow ${latestStarflowVersion}. Every link points to a Markdown copy of the page; drop the .md suffix for the HTML version. The full text of every page is in https://docs.starlake.ai/llms-full.txt.`,
        ].join("\n"),
        docsDir: [
          {
            path: `qod_versioned_docs/version-${latestQodVersion}`,
            routeBasePath: "qod",
            label: "Quack on Demand",
          },
          {
            path: `versioned_docs/version-${latestStarflowVersion}`,
            routeBasePath: "starflow",
            label: "Starflow",
          },
        ],
        includeOrder: sidebarOrderGlobs(
          `./qod_versioned_sidebars/version-${latestQodVersion}-sidebars.json`,
          `qod_versioned_docs/version-${latestQodVersion}`,
        ),
        ignoreFiles: ["superpowers/**"],
        generateMarkdownFiles: true,
        excludeImports: true,
        removeDuplicateHeadings: true,
        rewriteImageUrls: true,
      },
    ],
    [
      require.resolve("docusaurus-plugin-image-zoom"),
      {
        hashed: true,
      },
    ],
    [
      '@docusaurus/plugin-sitemap',
      {
        id: 'sitemap1',
        changefreq: 'weekly',
        priority: 0.5,
        ignorePatterns: ['/tags/**'],
        filename: 'sitemap.xml',
      },
    ],
  ].filter(Boolean),
  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },
  themes: ["@docusaurus/theme-mermaid"],
  // Per-section GA4 properties, in addition to the site-wide gtag above.
  // Read at build time; an unset variable disables that section's tag.
  customFields: {
    qodGaId: process.env.QOD_DOCS_GA_ID,
    starflowGaId: process.env.STARFLOW_DOCS_GA_ID,
    qodVersion,
  },
  clientModules: isBlog ? [] : [require.resolve("./src/clientModules/sectionAnalytics.js")],
};

module.exports = config;
